task: persona_punctuation_density
include: _defaults.yaml
process_results: !function utils.process_results_punctuation_density
metric_list:
  - metric: punctuation_density.count
    aggregation: mean
    higher_is_better: false
  - metric: punctuation_density.density
    aggregation: mean
    higher_is_better: false
