task: persona_verb_count
include: _defaults.yaml
process_results: !function utils.process_results_verb_count
metric_list:
  - metric: verb_count.count
    aggregation: mean
    higher_is_better: false
  - metric: verb_count.density
    aggregation: mean
    higher_is_better: false
