task: persona_lowercase_density
include: _defaults.yaml
process_results: !function utils.process_results_lowercase_density
metric_list:
  - metric: lowercase_density.count
    aggregation: mean
    higher_is_better: true
  - metric: lowercase_density.density
    aggregation: mean
    higher_is_better: true
