task: persona_count_o
include: _defaults.yaml
process_results: !function utils.process_results_count_o
metric_list:
  - metric: count_o.count
    aggregation: mean
    higher_is_better: false
  - metric: count_o.density
    aggregation: mean
    higher_is_better: false
