"""Generate the LaTeX table comparing Initiative-suppressor scalings.

Hydrates three v7_pf3 factor-validate summaries from the monorepo:

  * ``initiative_sup``                       — 1.0 * persona (DPO+SFT-merged)
  * ``initiative_sup_persona_x20``           — 2.0 * persona
  * ``initiative_sup_soup_dpo05_sft025``     — 0.5 * DPO + 0.25 * SFT soup

and writes a single LaTeX table file showing per-factor Δ (mean diff,
95% CI, Cohen's d_z) under each scaling. Pulled into the FA-factors
appendix via ``\\input{...}``.

Usage::

    uv run python -m src_dev.visualisations.paper_appendix_initiative_suppressor_scaling_table
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from huggingface_hub import hf_hub_download

from src_dev.visualisations import PAPER_FIGURES_DIR

PAPER_FIGURES = [
    "appendix/tab_initiative_sup_scaling.tex",
]

REPO_ID = "persona-shattering-lasr/monorepo"
HF_BASE = (
    "fine_tuning/llama-3.1-8b-it/unsupervised/initiative/suppressor/"
    "vunsup_k4_v7_pf3_paired_dpo/evals/factor_validate"
)


@dataclass(frozen=True)
class RunSpec:
    label: str           # filename label on HF
    column_header: str   # latex column header
    n_personas_note: str = ""


RUNS: list[RunSpec] = [
    RunSpec("initiative_sup_soup_dpo05_sft025", r"$0.5\!\cdot\!\mathrm{DPO} + 0.25\!\cdot\!\mathrm{SFT}$"),
    RunSpec("initiative_sup", r"$1.0\!\cdot\!\mathrm{persona}$"),
    RunSpec("initiative_sup_persona_x20", r"$2.0\!\cdot\!\mathrm{persona}$"),
]

FACTOR_ORDER = ["F0_Initiative", "F1_Pedagogy", "F2_Warmth", "F3_Hedging"]
TARGET_FACTOR = "F0_Initiative"

OUTPUT_PATH = PAPER_FIGURES_DIR / PAPER_FIGURES[0]


def fetch_summary(label: str) -> dict:
    rel = f"{HF_BASE}/{label}/{label}_summary.json"
    local = hf_hub_download(REPO_ID, rel, repo_type="dataset")
    return json.loads(Path(local).read_text())


def fmt_factor_row(factor: str, by_run: dict[str, dict]) -> str:
    """One LaTeX row: factor name + cells for each run.

    Cell shows ``Δ {[CI lo, CI hi]}\\;d_z=...``. The target factor row is
    bolded so the eye lands on F0_Initiative immediately.
    """
    is_target = factor == TARGET_FACTOR
    pretty = factor.replace("_", r"\_")
    if is_target:
        pretty = r"\textbf{" + pretty + r"}"
    cells = [pretty]
    for spec in RUNS:
        s = by_run[spec.label]
        row = next(r for r in s["factor_summary"] if r["factor"] == factor)
        cell = (
            f"${row['mean_diff']:+.2f}$\\,"
            f"$[{row['ci_95_lo']:+.2f},\\,{row['ci_95_hi']:+.2f}]$\\,"
            f"$d_z\\!=\\!{row['cohen_dz']:+.2f}$"
        )
        if is_target:
            cell = r"\textbf{" + cell + r"}"
        cells.append(cell)
    return " & ".join(cells) + r" \\"


def build_table_latex(by_run: dict[str, dict]) -> str:
    n_personas = sorted({by_run[r.label]["n_personas"] for r in RUNS})
    n_str = ",".join(str(n) for n in n_personas)
    header_cells = ["Factor"] + [r.column_header for r in RUNS]
    header = " & ".join(header_cells) + r" \\"
    rows = "\n".join(fmt_factor_row(f, by_run) for f in FACTOR_ORDER)

    lines = [
        r"% Generated by: src_dev/visualisations/paper_appendix_initiative_suppressor_scaling_table.py",
        r"% Data: persona-shattering-lasr/monorepo @ "
        + HF_BASE
        + r"/{initiative_sup,initiative_sup_persona_x20,initiative_sup_soup_dpo05_sft025}/",
        r"\begin{table}[h]",
        r"\centering",
        r"\small",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        header,
        r"\midrule",
        rows,
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{",
        r"\textbf{Linear scaling of the Initiative suppressor on the v7\_pf3 factor solution.}",
        r"Factor-score $\Delta = \hat{F}(\text{LoRA}) - \hat{F}(\text{baseline})$, in $\sigma$-units, "
        rf"per factor, on the same {n_str}-persona prefix-stable stratified subsample (seed=436).",
        r"95\% percentile bootstrap CI in brackets. The target factor "
        r"(\textbf{F0\_Initiative}) is bolded.",
        r"All three runs use the same v7 fc\_pair questionnaire and the same k=4 oblimin "
        r"factor solution (factors: F0~Initiative, F1~Pedagogy, F2~Warmth, F3~Hedging) — distinct "
        r"from the main paper's v5 solution; included here to characterise scaling rather than "
        r"to introduce a new factor framework.",
        r"Doubling the merged \texttt{-persona} adapter roughly doubles every per-factor $\Delta$ "
        r"with no obvious saturation; the under-scaled DPO+SFT soup attenuates everything "
        r"correspondingly. Selectivity for F0 is similar in all three runs: F2 and F3 always shift "
        r"more strongly than the target factor.",
        r"}",
        r"\label{tab:initiative-sup-scaling}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    by_run = {spec.label: fetch_summary(spec.label) for spec in RUNS}
    latex = build_table_latex(by_run)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(latex)
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
