"""Build a TRAIT-benchmark questionnaire for the psychometric FA pipeline.

Pulls N samples per OCEAN trait from the `mirlab/TRAIT` benchmark, shuffles the
A/B/C/D options per-sample (deterministic with `seed`), and writes a
questionnaire JSON that slots into the existing `block_4_trait_mcq` item type
in `psychometric_rollout_fa.py`.

Each emitted item carries:
- `question`          — the TRAIT scenario/question text
- `options`           — [{label: "A", text: ...}, ...] after shuffle
- `answer_mapping`    — {letter: 1 if high-trait, 0 if low-trait} for the
                        shuffled positions (from inspect_evals' enrichment)
- `primary_dimension` — OCEAN trait, lower-cased (openness, ...)

Usage:
    uv run python scripts_dev/unsupervised_embeddings/build_trait_questionnaire.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from src_dev.evals.inspect_benchmarks import _load_trait_dataset

OCEAN_SPLITS = [
    "Openness",
    "Conscientiousness",
    "Extraversion",
    "Agreeableness",
    "Neuroticism",
]

SAMPLES_PER_TRAIT = 20
SHUFFLE_SEED = 42


# Every upstream TRAIT question follows the pattern
#   "<trait-priming statement>. <behavioural question>"
# The priming statement is a trait-positive "fact" (e.g.
# "Appreciating beauty can enhance one's quality of life and sense of
# fulfillment.") which may bias responses toward the high-pole options
# independent of the model's actual disposition. Set STRIP_LEADIN=True
# to drop the first sentence and keep only the behavioural question.
# Verified for all 100 items: every question has a clean sentence
# boundary (". " followed by a capital letter).
_LEADIN_PATTERN = re.compile(r"^[^.]*?\. (?=[A-Z])")


def _strip_leadin(question: str) -> str:
    """Strip the first-sentence trait-priming lead-in from a TRAIT question."""
    return _LEADIN_PATTERN.sub("", question, count=1)


def _build_items(*, strip_leadin: bool) -> list[dict]:
    items: list[dict] = []
    for split in OCEAN_SPLITS:
        ds = _load_trait_dataset(
            samples_per_trait=SAMPLES_PER_TRAIT,
            trait_splits=[split],
            shuffle_choices=True,
            seed=SHUFFLE_SEED,
        )
        trait_lower = split.lower()
        for s in ds:
            options = [
                {"label": chr(ord("A") + i), "text": choice}
                for i, choice in enumerate(s.choices)
            ]
            question = _strip_leadin(s.input) if strip_leadin else s.input
            items.append({
                "id": f"{trait_lower}_{s.id}",
                "question": question,
                "options": options,
                "answer_mapping": dict(s.metadata["answer_mapping"]),
                "primary_dimension": trait_lower,
            })
    return items


# (version tag, strip-leadin flag, output filename) — main() writes any
# variant whose output file doesn't already exist; v1 is intentionally
# not regenerated by default so existing HF caches stay valid.
VARIANTS: list[tuple[str, bool, str]] = [
    ("trait_ocean_v1", False, "trait_ocean_v1.json"),
    ("trait_ocean_v1_nolead", True, "trait_ocean_v1_nolead.json"),
]

OUTPUT_DIR = Path("datasets/psychometric_questionnaires")


def main() -> None:
    for version, strip_leadin, filename in VARIANTS:
        out_path = OUTPUT_DIR / filename
        if out_path.exists():
            print(f"[skip] {out_path} already exists — not overwriting.")
            continue
        items = _build_items(strip_leadin=strip_leadin)
        description = (
            f"TRAIT benchmark (mirlab/TRAIT), {SAMPLES_PER_TRAIT} questions per "
            f"OCEAN trait ({', '.join(OCEAN_SPLITS)}). Options shuffled per item "
            f"with seed={SHUFFLE_SEED}. answer_mapping reflects shuffled positions."
        )
        if strip_leadin:
            description += (
                " Trait-priming lead-in sentence stripped from every question "
                "(first-sentence removal); only the behavioural question remains."
            )
        payload = {
            "version": version,
            "description": description,
            "source": "mirlab/TRAIT",
            "shuffle_seed": SHUFFLE_SEED,
            "samples_per_trait": SAMPLES_PER_TRAIT,
            "splits": OCEAN_SPLITS,
            "dimensions": [t.lower() for t in OCEAN_SPLITS],
            "strip_leadin": strip_leadin,
            "block_4_trait_mcq": {
                "description": (
                    "MCQ items with 4 options (A/B/C/D). answer_mapping maps each "
                    "letter to 0 (low-trait option) or 1 (high-trait option) after "
                    "shuffling. For unsupervised FA the raw choice is encoded as "
                    "integer 1..4 (A=1, B=2, C=3, D=4); for TRAIT scoring the "
                    "answer_mapping is used directly."
                ),
                "items": items,
            },
        }

        out_path = OUTPUT_DIR / filename
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)

        print(
            f"Wrote {len(items)} items ({len(OCEAN_SPLITS)} traits × "
            f"{SAMPLES_PER_TRAIT}) to {out_path}  (strip_leadin={strip_leadin})"
        )


if __name__ == "__main__":
    main()
