"""Train a LoRA adapter via DPO on extraversion data pairs.

Reads DPO pairs from the JSONL generated by generate_extraversion_dpo_data.py
and fine-tunes a LoRA adapter using TRL's DPOTrainer.

Hyperparameters match OCT's llama.sh (OpenRLHF DPO) as closely as possible.

Usage:
    python scripts_dev/oct_pipeline/train_extraversion_dpo.py
"""

from __future__ import annotations

import datetime
import gc
import itertools
import json
import shutil
import subprocess
import time
from pathlib import Path

import datasets as hf_datasets
import torch
from dotenv import load_dotenv
from peft import LoraConfig, TaskType, get_peft_model
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import DPOConfig, DPOTrainer

from src_dev.utils.hf_hub import upload_folder_to_dataset_repo

load_dotenv()

# ---------------------------------------------------------------------------
# Config — edit these directly
# ---------------------------------------------------------------------------

DPO_DATA_PATH = "scratch/oct/extraversion/dpo_pairs3.jsonl"
BASE_MODEL = "meta-llama/Meta-Llama-3.1-8B-Instruct"
SAVE_PATH = "scratch/oct/extraversion/lora/extraversion-dpo3"

# LoRA
LORA_RANK = 64
LORA_ALPHA = 128
LORA_DROPOUT = 0.05

# DPO training
LEARNING_RATE = 5e-5
NUM_EPOCHS = 1
BETA = 0.1
MAX_LEN = 1024
NLL_LOSS_COEF = 0.1
BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 16
SEED = 123456

# Filtering
MIN_RESPONSE_LENGTH = 100  # chars

# HuggingFace upload
HF_REPO = "persona-shattering-lasr/monorepo"
# HF_DIR = "fine_tuning/llama-3.1-8B-Instruct/ocean/extraverted/dpo/model"
HF_DIR = "fine_tuning/llama-3.1-8B-Instruct/ocean/extraverted/dpo3/model"

# HuggingFace data source
HF_DATA_DIR = "fine_tuning/llama-3.1-8B-Instruct/ocean/extraverted/dpo3/data"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


_REFUSAL_PHRASES = [
    # "i don't have personal",
    # "i don't have feelings",
    # "i don't have emotions",
    # "i don't experience",
    # "i don't truly have",
    # "i don't actually have",
    # "i can't feel",
    # "i don't feel emotions",
    # "i'm not capable of feeling",
    # "i lack personal",
]


def _is_bad_response(text: str) -> bool:
    """Check if a response should be filtered (refusal or too short)."""
    if len(text) < MIN_RESPONSE_LENGTH:
        return True
    lower = text.lower()
    return any(phrase in lower for phrase in _REFUSAL_PHRASES)


def _expand_and_convert(records: list[dict]) -> list[dict]:
    """Expand compact {prompt, chosen: [...], rejected: [...]} into DPO pairs.

    Each record has lists of chosen/rejected responses. We take the cartesian
    product and convert to conversational format for TRL's DPOTrainer.
    Filters out responses that contain refusal phrases.
    """
    out = []
    filtered_chosen = 0
    filtered_rejected = 0
    for r in records:
        chosen_list = r["chosen"] if isinstance(r["chosen"], list) else [r["chosen"]]
        rejected_list = (
            r["rejected"] if isinstance(r["rejected"], list) else [r["rejected"]]
        )

        clean_chosen = [c for c in chosen_list if not _is_bad_response(c)]
        clean_rejected = [rej for rej in rejected_list if not _is_bad_response(rej)]
        filtered_chosen += len(chosen_list) - len(clean_chosen)
        filtered_rejected += len(rejected_list) - len(clean_rejected)

        for c, rej in itertools.product(clean_chosen, clean_rejected):
            out.append(
                {
                    "chosen": [
                        {"role": "user", "content": r["prompt"]},
                        {"role": "assistant", "content": c},
                    ],
                    "rejected": [
                        {"role": "user", "content": r["prompt"]},
                        {"role": "assistant", "content": rej},
                    ],
                }
            )

    print(
        f"  Filtered out {filtered_chosen} chosen + {filtered_rejected} rejected bad responses (refusals or <{MIN_RESPONSE_LENGTH} chars)"
    )
    return out


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def _ensure_dpo_data() -> None:
    """Download DPO pairs from HuggingFace if not present locally."""
    path = Path(DPO_DATA_PATH)
    if path.exists():
        return
    from huggingface_hub import hf_hub_download

    print(f"  {DPO_DATA_PATH} not found — downloading from {HF_REPO}/{HF_DATA_DIR}")
    path.parent.mkdir(parents=True, exist_ok=True)
    hf_hub_download(
        repo_id=HF_REPO,
        filename="dpo_pairs3.jsonl",
        subfolder=HF_DATA_DIR,
        repo_type="dataset",
        local_dir=str(path.parent),
    )
    # hf_hub_download places the file in a subfolder mirror; move it to expected path
    downloaded = path.parent / HF_DATA_DIR / "dpo_pairs3.jsonl"
    if downloaded.exists() and not path.exists():
        downloaded.rename(path)
    print(f"  Downloaded to {path}")


def main() -> None:
    # Load data
    _ensure_dpo_data()
    records = []
    with open(DPO_DATA_PATH) as f:
        for line in f:
            records.append(json.loads(line))
    print(f"Loaded {len(records)} DPO pairs from {DPO_DATA_PATH}")

    save_path = Path(SAVE_PATH)

    print(f"\n{'=' * 70}")
    print("DPO TRAINING")
    print(f"  model:     {BASE_MODEL}")
    print(f"  pairs:     {len(records)}")
    print(f"  lora:      rank={LORA_RANK}  alpha={LORA_ALPHA}")
    print(
        f"  batch:     {BATCH_SIZE} x {GRADIENT_ACCUMULATION_STEPS} = {BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS}"
    )
    print(f"  nll_loss:  {NLL_LOSS_COEF}")
    print(f"  save_path: {save_path}")
    print(f"{'=' * 70}")

    # Check GPU
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA not available.")
    free, total = torch.cuda.mem_get_info(0)
    free_gib = free / 1024**3
    print(f"  GPU free: {free_gib:.1f} / {total / 1024**3:.1f} GiB")
    if free_gib < 10.0:
        raise RuntimeError(
            f"Not enough GPU memory ({free_gib:.1f} GiB free, need >= 10 GiB)"
        )

    # Tokenizer
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Expand combinations and convert to conversational format
    conv_records = _expand_and_convert(records)
    print(f"Expanded to {len(conv_records)} DPO pairs")
    dataset = hf_datasets.Dataset.from_list(conv_records)

    # Load model
    print("  Loading base model...")
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        trust_remote_code=True,
    )

    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=LORA_RANK,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        bias="none",
        target_modules="all-linear",
    )
    model = get_peft_model(base_model, lora_config)
    model.print_trainable_parameters()

    # DPO config — matches OCT's llama.sh
    training_args = DPOConfig(
        output_dir=str(save_path),
        num_train_epochs=NUM_EPOCHS,
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
        learning_rate=LEARNING_RATE,
        adam_beta1=0.9,
        adam_beta2=0.98,
        lr_scheduler_type="cosine",
        warmup_ratio=0.1,
        bf16=True,
        fp16=False,
        max_grad_norm=1.0,
        logging_steps=1,
        save_strategy="no",
        seed=SEED,
        beta=BETA,
        loss_type=["sigmoid", "sft"],
        loss_weights=[1.0, NLL_LOSS_COEF],
        max_length=MAX_LEN,
        remove_unused_columns=False,
        report_to="none",
        precompute_ref_log_probs=True,
        gradient_checkpointing=True,
    )

    trainer = DPOTrainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
        processing_class=tokenizer,
    )

    print("  Starting DPO training...")
    start_time = time.time()
    trainer.train()
    elapsed = time.time() - start_time

    save_path.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(str(save_path))
    tokenizer.save_pretrained(str(save_path))
    print(f"  DPO adapter saved to: {save_path}")

    # Upload to HuggingFace: model files + script + run info
    git_hash = subprocess.run(
        ["git", "rev-parse", "HEAD"], capture_output=True, text=True
    ).stdout.strip()

    train_log = trainer.state.log_history
    final_loss = train_log[-1].get("train_loss") if train_log else None

    run_info = {
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "git_hash": git_hash,
        "elapsed_seconds": round(elapsed, 1),
        "base_model": BASE_MODEL,
        "dpo_data_path": DPO_DATA_PATH,
        "num_records": len(records),
        "num_dpo_pairs": len(conv_records),
        "lora_rank": LORA_RANK,
        "lora_alpha": LORA_ALPHA,
        "lora_dropout": LORA_DROPOUT,
        "learning_rate": LEARNING_RATE,
        "num_epochs": NUM_EPOCHS,
        "beta": BETA,
        "max_length": MAX_LEN,
        "nll_loss_coef": NLL_LOSS_COEF,
        "batch_size": BATCH_SIZE,
        "gradient_accumulation_steps": GRADIENT_ACCUMULATION_STEPS,
        "effective_batch_size": BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS,
        "seed": SEED,
        "final_train_loss": final_loss,
    }

    # Copy script and run_info into the save dir for a single folder upload
    shutil.copy2(Path(__file__), save_path / Path(__file__).name)
    (save_path / "run_info.json").write_text(json.dumps(run_info, indent=2))

    url = upload_folder_to_dataset_repo(
        local_dir=save_path,
        repo_id=HF_REPO,
        path_in_repo=HF_DIR,
        commit_message=f"extraversion DPO adapter: {len(conv_records)} pairs, loss={final_loss}",
    )
    print(f"  Uploaded to {url}")

    del trainer, model, base_model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()


if __name__ == "__main__":
    main()
